site_name: Form History Control (II)
site_author: S.J. Mahieu
copyright:
docs_dir: docsource
site_dir: docs
theme: readthedocs
pages:
- Home: index.md
- Manual:
  - Introduction: Manual\manual.md
  - Frequently Asked Questions: Manual\FAQ.md
  - Known Issues: Manual\KnownIssues.md
- FHC Export:
  - FHC Export: FHCExport\FHCExport.md
- Release Notes: ReleaseNotes\releasenotes.md
- About: about.md
