# Project information
site_name: Form History Control (II)
site_author: S.J. Mahieu

# Copyright
copyright: Copyright &copy; 2020 Stephan Mahieu

# Configuration
docs_dir: docsource
site_dir: docs
theme:
    name: material
    language: en
    custom_dir: custom_theme
    #feature:
    #    tabs: true
    logo: assets/images/fhc_icon.svg
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details


# Customization
extra:
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/stephanmahieu/formhistorycontrol-2
    - icon: fontawesome/brands/firefox
      link: https://addons.mozilla.org/firefox/addon/form-history-control?src=github-pages
    - icon: fontawesome/brands/chrome
      link: https://chrome.google.com/webstore/detail/form-history-control-ii/lpcccgcdjibejkgiaeijbmkpbnbkglkb
    - icon: fontawesome/brands/blogger
      link: https://formhistory.blogspot.com/
    # - icon: fontawesome/brands/linkedin
    #  link: https://linkedin.com/in/stephanm/

# Navigation structure
nav:
- Home: index.md
- Manual:
  - Introduction: Manual\manual.md
  - Frequently Asked Questions: Manual\FAQ.md
  - Permissions: Manual\Permissions.md
  - Known Issues: Manual\KnownIssues.md
  - Tranlating FHC: Manual\Translation.md
- Release Notes: ReleaseNotes\fhc-releasenotes.md
- Project Page: project.md
- FHC Export: FHCExport.md
- Privacy Policy: privacy.md
- About: about.md
